# Example parameter file for jasperstarter.
# Use one key=value pair per line. Commas belong to the value and do not separate parameters.

Reportpath=/app/httpdocs/filemanager/reports/calibrations/dakks-sample
PrefixTable=
Sprache=Deutsch
QR_Code_Value=https://metweb2.emea.thermo.com/inventory/qrcode/200097%3A945766005
P_CTAG=812d117c-d2ce-4e0a-93e9-0e8e7ff3de97
MeasurementDetails=
ModernResultsHeader=
ReportVariantCode=
Cert_description=Dieser Kalibrierschein dokumentiert die Rückführung auf nationale Normale zur Darstellung der Einheiten in Übereinstimmung mit dem Internationalen Einheitensystem (SI). Die DAkkS ist Unterzeichner der multilateralen Übereinkommen der European co-operation for Accreditation (EA) und der International Laboratory Accreditation Cooperation (ILAC) zur gegenseitigen Anerkennung der Kalibrierscheine. <br/>Für die Einhaltung einer angemessenen Frist zur Wiederholung der Kalibrierung ist der Benutzer verantwortlich. <br/>Die den Messwerten beigeordnete erweiterte Messunsicherheit ergibt sich aus der Standardmessunsicherheit durch Multiplikation mit dem Erweiterungsfaktor k = 2. Sie wurde gemäß DAkkS DKD-3 ermittelt. Der Wert der Messgröße liegt mit einer Wahrscheinlichkeit von 95% im zugeordneten Werteintervall.
Cert_description_1=Dieser Kalibrierschein darf nur vollständig und unverändert weiterverbreitet werden. Auszüge oder Änderungen bedürfen der Genehmigung sowohl der Deutschen Akkreditierungsstelle als auch des ausstellenden Kalibrierlaboratoriums. Kalibrierscheine ohne Unterschrift haben keine Gültigkeit.
Asset_description=[T4102] here...<br/><br/>exakt handelte es sich um ein:<br/>PREMA 5017 mit der Serial: 1075011
Results_description=Die Messergebnisse sind ab Seite {0} wiedergegeben. Alle angegebenen Messergebnisse beschreiben den kalibrierten Gegenstand zum Zeitpunkt und am Ort der Kalibrierung. Eine Aussage über das Langzeitverhalten ist damit nicht verbunden.
Results_end_note=
Measurements_description=Angegeben ist die erweiterte Messunsicherheit, die sich aus der Standardmessunsicherheit durch Multiplikation mit dem Erweiterungsfaktor k = 2 ergibt. Sie wurde gemäß DAkkS-DKD-3 bzw. EA 4/2 ermittelt. Der Wert der Messgröße liegt mit einer Wahrscheinlichkeit von ca. 95 % im zugeordneten Werteintervall.
Measurements_description_1=Die Messunsicherheiten wurden mit der Software \u2018GUM-Workbench\u2019 abgeschätzt, die Ergebnisse werden dokumentiert.
Uncertainty_description=
Conformity_description_1=Sofern Konformitätsaussagen erfolgen, werden diese unter Berücksichtigung der Messunsicherheit gemacht.<br/>Einschränkungen werden wie folgt gekennzeichnet:
Conformity_description_2=?<br/><br/><br/>!?<br/><br/><br/>!<br/><br/>*
Conformity_description_3=Messwert innerhalb der Herstellerspezifikationen. Es kann jedoch unter Berücksichtigung der Messunsicherheit keine Konformitätsaussage gemacht werden.<br/><br/>Messwert außerhalb der Herstellerspezifikationen. Es kann jedoch unter Berücksichtigung der Messunsicherheit keine negative Konformitätsaussage gemacht werden.<br/><br/>Messwert außerhalb der Herstellerspezifikationen.<br/><br/>Messergebnisse nicht im Akkreditierungsumfang des Kalibrierlaboratoriums.
Additional_information=Die Deutsche Akkreditierungsstelle GmbH ist Unterzeichner der multilateralen Übereinkommen der European Cooperation for Accreditation (EA) und der International Laboratory Accreditation Cooperation (ILAC) zur gegenseitigen Anerkennung der Kalibrierscheine. Die weiteren Unterzeichner innerhalb und außerhalb Europas sind den Internetseiten von EA (www.european-accreditation.org) und ILAC (www.ilac.org) zu entnehmen.
Calibration_procedure_1=Kalibrierung gemäß interner Verfahrensanweisung unter Verwendung rückgeführter Normale.
Calibration_document=Kalibrierung gemäß gültiger interner Verfahrensanweisung.
Calibration_procedure_2=Computergestützte Kalibrierung gemäß gültiger interner Verfahrensanweisung.
Cert_field=C2396
P_Image_Path=/app/httpdocs/filemanager/uploads/results/calibration/
ExpUncType=
ReportVersion=
MarkNumber1=
MarkNumber2=
sign_names=
ShowGroup1CalibrationItem=
ShowGroup1IncomingDate=
IncomingDate_override=
ShowGroup1Condition=
Condition_override=
ShowGroup1Spacer=
ShowGroup1Procedure=
ShowGroup1ProcedureDocument=
ShowGroup1MeasurementConditions=
ShowGroup1CalibrationPlace=
CalibrationPlace_override=
ShowGroup1EnvironmentalConditions=
environmental_conditions=
ShowGroup1StandardsTraceability=
ShowGroup1ResultsIntro=
ShowGroup1MeasurementUncertainty=
ShowGroup1Conformity=
ShowGroup1AdditionalInformation=
ShowGroup1ResultsDetails=
