---
name: Release Reports

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v1.2.3)'
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create ZIP archives
        run: |
          mkdir -p output
          zip -r output/dakks-sample.zip \
            DAKKS-SAMPLE/main_reports DAKKS-SAMPLE/subreports -x "*.zip"
          zip -r output/order-sample.zip \
            ORDER-SAMPLE/main_reports ORDER-SAMPLE/subreports -x "*.zip"
          zip -r output/inventory-sample.zip \
            INVENTORY-SAMPLE/main_reports INVENTORY-SAMPLE/subreports -x "*.zip"

      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
          files: output/*.zip
          generate_release_notes: true
