---
name: Release Reports

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v1.2.3)'
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create ZIP archives
        run: |
          mkdir -p output
          (cd DAKKS-SAMPLE && zip -r ../output/dakks-sample.zip main_reports subreports)
          (cd ORDER-SAMPLE && zip -r ../output/order-sample.zip main_reports subreports)
          (cd INVENTORY-SAMPLE && zip -r ../output/inventory-sample.zip main_reports subreports)

      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
          files: output/*.zip
          generate_release_notes: true
